/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fgffimxekshjrrnwndcd"
export const supabaseUrl = 'https://fgffimxekshjrrnwndcd.supabase.co'
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZmZpbXhla3NoanJybnduZGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTM5MTUsImV4cCI6MjA3MzM2OTkxNX0.AnWquapxkzhNWSF-KX5c9hMiSywl7xSTnBLtGvctG9o'
